### ISSUE TITLE
Editable Voids Example Crashes

### ISSUE THREAD

**Issue by bmingles** [slate-solid/slate-solid#45]
Selecting all content and hitting backspace crashes the editor in Editable voids sample

```
with-solid-Cc_BlO_D.js:6 Uncaught (in promise) Error: Cannot find a descendant at path [2,0] in node: {"children":[{"type":"paragraph","children":[{"text":""}]}],"operations":[{"type":"remove_text","path":[0,0],"offset":0,"text":"In addition to nodes that contain editable text, you can insert void nodes, which can also contain editable elements, inputs, or an entire other Slate editor."},{"type":"remove_node","path":[1],"node":{"type":"editable-void","children":[{"text":""}]}},{"type":"remove_node","path":[0],"node":{"type":"paragraph","children":[{"text":""}]}}],"selection":{"anchor":{"path":[0,0],"offset":0},"focus":{"path":[0,0],"offset":0}},"marks":null,"history":{"undos":[{"operations":[{"type":"remove_text","path":[0,0],"offset":0,"text":"In addition to nodes that contain editable text, you can insert void nodes, which can also contain editable elements, inputs, or an entire other Slate editor."},{"type":"remove_node","path":[1],"node":{"type":"editable-void","children":[{"text":""}]}},{"type":"remove_node","path":[0],"node":{"type":"paragraph","children":[{"text":""}]}}],"selectionBefore":{"anchor":{"path":[0,0],"offset":0},"focus":{"path":[2,0],"offset":0}}}],"redos":[]}}
    at Object.get (with-solid-Cc_BlO_D.js:6:23645)
    at Object.first (with-solid-Cc_BlO_D.js:6:22918)
    at hs (with-solid-Cc_BlO_D.js:6:73130)
    at Object.point (with-solid-Cc_BlO_D.js:6:100422)
    at Object.point (with-solid-Cc_BlO_D.js:6:30993)
    at ws (with-solid-Cc_BlO_D.js:6:76327)
    at Object.start (with-solid-Cc_BlO_D.js:6:102097)
    at Object.start (with-solid-Cc_BlO_D.js:6:31357)
    at Es (with-solid-Cc_BlO_D.js:6:75277)
    at Object.range (with-solid-Cc_BlO_D.js:6:100976)
```

**Comment by bmingles** [comment]
I think I know what’s happening here. It seems that the week refs for the parent no are stale. In this particular case I need to see if I can update week refs across the state tree and a more dependable way.

**Comment by bmingles** [comment]
@Noobulater I think this PR should fix this bug (+ probably some others we haven't seen yet)
https://github.com/slate-solid/slate-solid/pull/47

I'll keep the void thing in mind though as I think there may still be cases that haven't been tested. TBD whether that nuance will surface.
